### ISSUE TITLE
Adding the footer with feedback.

### ISSUE THREAD

**Issue by CrypticRevenger** [shravan20/github-readme-quotes#259] opened 2023-10-09 05:54 UTC
Context:

Create a simple feedback form in the footer and integrate the response to be directly picked up on formspree.

![image](https://github.com/shravan20/github-readme-quotes/assets/47430686/0490efea-6036-47f0-b41a-dec1a01c8c2b)

Drop us a message form can submitted to https://formspree.io/ ; to collect any feedback people would like to raise.

Sitemap can contain:
- About Us (Redirecting to github page)
- Contact Us (hyperlinked with shravan@ohmyscript.com)
- Terms & Conditions (license file)

**Comment by shravan20** [comment] 2023-10-09 06:00
@CrypticRevenger: Amazing, assigning this to you!! :D

**Comment by AviGawande** [comment] 2023-10-12 17:04
@shravan20 i would like to contribute to this repo

**Comment by RAJASHEKARGUNAGANTI** [comment] 2024-05-20 02:06
Hi @shravan20  I would like to contribute for this repo 
And some more insights about feature update is appreciated.

**Comment by shravan20** [comment] 2024-05-20 13:13
@RAJASHEKARGUNAGANTI : This is open for picking up! You can take it up for dev

**Comment by PavanVarma474** [comment] 2024-05-27 02:19
@shravan20 can you please elaborate more on the issue, i could understand that you need a footer that allows users to give a feedback , is it? if so where you wanted to go that feedback to?

**Comment by shravan20** [comment] 2024-05-27 18:30
Simple footer to take the feedback from the users and collate it in https://formspree.io/

Can pass the formspree URL from .env, I will replace it with custom URL, for now you can use an test URL from your end.

**Comment by shravan20** [comment] 2024-05-27 18:32
@PavanVarma474 : Reassigned this to you

**Comment by nikhilnishadoo7** [comment] 2024-06-26 19:11
is the issue is still open? i want to work on it

**Comment by shravan20** [comment] 2024-06-26 19:48
Yes, this is open. You can pick it up

**Comment by akhilk2802** [comment] 2024-07-03 12:53
is this issue solved and merged ?

**Comment by RajatX24** [comment] 2024-10-05 05:49
Hello, My name is Rajat Shukla and i would like to work on this issue. Is it still open and unassigned?

(My previous experience includes building a MERN stack based chess website which allowed users to chat,play,read articles and news. I used MUI in that project and hence i feel confident that I'll be able to do this successfully.)

**Comment by shravan20** [comment] 2024-10-05 06:04
Hey, sure. Feel free to pick this up!! And raise a PR

**Comment by RajatX24** [comment] 2024-10-06 08:38
hello @shravan20,
I have completed the work and have opened a pull request for the same
You can see it here: https://github.com/shravan20/github-readme-quotes/pull/323

I would be grateful if you could review it. 
In case you merge it please mark it as 'hacktoberfest-accepted'. I would be grateful.

Thanks!

**Comment by Aishwarya-S-Sharma** [comment] 2024-10-10 20:29
hello @shravan20, is this still open?

**Comment by shravan20** [comment] 2024-10-10 20:33
This is already done, PR is ready to be released this weekend. You can pick up any other issues.

**Comment by Aishwarya-S-Sharma** [comment] 2024-10-11 10:21
sure thanks

**Closed** 2024-10-15 08:22 UTC
Labels: enhancement, help wanted, good first issue, Medium work, hacktoberfest-accepted, hacktoberfest, frontend
