### ISSUE TITLE
Issue with template themes

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#314] opened 2024-09-11 09:58 UTC
**Describe the bug**

Due to some recent change something has messed up quite a lot with background color, font color etc from themes selected

**Expected behavior**
This is happening on the API and UI bit as well.

**Screenshots**

Expected design:

![image](https://github.com/user-attachments/assets/d4c612a5-b7c5-4344-862c-1541a3bceb2b)

Actual design:

![image](https://github-readme-quotes-bay.vercel.app/quote?theme=synthwave&animation=default&layout=default&font=default&fontColor=white&bgColor=black&quoteType=random)

**Additional context**

- This might be caused due to recent changes pushed to start with.

**Comment by yaodada123** [comment] 2024-09-12 10:37
@shravan20 
Can you assign this issue to me? I think I can try it

**Comment by shravan20** [comment] 2024-09-12 11:14
Sure, assigning it to you 🎉🎊

**Comment by 4nshuman** [comment] 2024-09-22 15:55
Hi @shravan20,
I think this issue is a duplicate of [Issue#253](https://github.com/shravan20/github-readme-quotes/issues/253)
And it I've solved it as a part of the latest [PR#316](https://github.com/shravan20/github-readme-quotes/pull/316)
Please take a look.

**Comment by shravan20** [comment] 2024-09-23 04:47
**_Marking this as resolved._**

**Closed** 2024-09-23 04:48 UTC
Labels: bug, help wanted, good first issue, Little work, hacktoberfest, frontend, backend, high
